// ============================================================
//  SIGMA HOVER GP — THE TRACKS  (EDIT ME!)
//
//  Every track is a list of pieces, driven one after another:
//    'straight 80'        drive straight for 80 meters
//    'right 90 50'        turn right 90 degrees, the curve is 50 m wide (radius)
//    'left 45 30'         turn left 45 degrees, tight curve
//    'jump 30'            a ramp, then fly over a 30 m hole!
//    'glide 80'           a big blue ramp: open your wings and glide 80 m
//    'loop'               a loop-the-loop!   'twist 100'  the road rolls all the way around
//    'width 30'           make the road wider from now on
//
//  Put extra words after a piece:
//    up 10 / down 10      go up or down 10 meters
//    bank 15              tilt the road in the curve
//    boost                a boost pad      boost-left / boost-right
//    items                a row of item boxes
//    coins                a line of coins  coins-left / coins-right
//    ramp                 a little trick ramp at the end
//    fall                 no walls: don't fall off!
//    cut                  a big grass corner you can cut with a turbo
//    off 10               10 m of offroad on each side
//    tunnel  water  ice  dirt  anti (anti-gravity glow)
//    hazard:roller  hazard:crusher  hazard:sweeper  hazard:geyser  hazard:car  hazard:ghost
//
//  The turns must add up to one full circle (360 degrees) so the
//  track comes back to the start. If the end doesn't quite meet the
//  start, the game bends the track a little bit to make it fit.
// ============================================================
window.HG = window.HG || {};

HG.TRACKS = [
  // ===================== 1. SIGMA CUP =====================
  {
    id: 'neon', name: 'NEON SIGMA CITY', cup: 0, theme: 'city', laps: 3, width: 24,
    course: [
      'straight 120 items2 coins',
      'right 90 45 bank 8',
      'straight 80 boost',
      'right 45 60',
      'left 90 40 bank 10 coins-right',
      'straight 40',
      'jump 28',
      'straight 70 items',
      'right 135 38 bank 12 cut',
      'straight 50 up 14 hazard:car 2',
      'left 60 60',
      'straight 30',
      'right 120 45 bank 10',
      'straight 120 down 14 boost coins',
      'right 90 40 tunnel',
      'straight 60 tunnel items',
      'right 30 80',
    ],
  },
  {
    id: 'beach', name: 'PALM BEACH', cup: 0, theme: 'beach', laps: 3, width: 26, offroad: 6,
    course: [
      'straight 110 items',
      'left 60 70',
      'straight 70 water coins',
      'right 90 45 bank 6',
      'straight 30',
      'jump 34',
      'straight 70 water boost',
      'left 150 45 bank 10 cut',
      'straight 80 coins-left',
      'left 60 70',
      'right 60 50',
      'straight 60 water items hazard:roller 2',
      'left 120 50 bank 12',
      'straight 90 boost2',
      'left 60 60',
      'straight 50',
      'left 60 80',
    ],
  },
  {
    id: 'candy', name: 'CANDY CANYON', cup: 0, theme: 'candy', laps: 3, width: 24,
    course: [
      'straight 90 items',
      'right 60 50 bank 10',
      'left 60 50 bank 10 coins',
      'right 120 40 bank 14',
      'straight 50 up 10 ramp',
      'straight 40 boost',
      'left 90 45 bank 10',
      'straight 70 hazard:roller 3 coins',
      'right 150 35 bank 18',
      'straight 40 down 10',
      'jump 26',
      'straight 50 items',
      'right 90 60',
      'left 45 50',
      'right 75 50 boost',
      'straight 60',
      'right 60 60',
    ],
  },
  {
    id: 'desert', name: 'DUNE RUN', cup: 0, theme: 'desert', laps: 3, width: 28, offroad: 8,
    course: [
      'straight 120 items2',
      'right 90 70 cut',
      'straight 100 dirt coins',
      'left 45 80',
      'straight 40',
      'jump 40',
      'straight 60 boost',
      'right 135 50 bank 8 cut',
      'straight 80 hazard:roller 2 dirt',
      'left 90 60',
      'right 90 50',
      'straight 70 items',
      'right 120 60 cut',
      'straight 100 down 8 boost2 coins',
      'right 60 80',
    ],
  },
  // ===================== 2. TURBO CUP =====================
  {
    id: 'ice', name: 'FROSTBITE PEAK', cup: 1, theme: 'ice', laps: 3, width: 24,
    course: [
      'straight 100 items',
      'left 90 50 bank 10',
      'straight 80 down 12 ice coins',
      'left 45 60',
      'right 135 40 bank 12',
      'straight 60 tunnel ice',
      'right 45 60 tunnel',
      'straight 50 tunnel boost',
      'jump 30',
      'straight 60 items',
      'left 120 45 bank 14 cut',
      'straight 80 up 12 hazard:roller 2',
      'left 90 50',
      'straight 60 boost coins',
      'left 150 50 bank 10',
      'straight 50',
      'left 45 70',
    ],
  },
  {
    id: 'jungle', name: 'JUNGLE RUINS', cup: 1, theme: 'jungle', laps: 3, width: 22, offroad: 5,
    course: [
      'straight 100 dirt items',
      'right 60 50',
      'left 90 40 bank 8 coins',
      'straight 60 tunnel hazard:crusher 2',
      'right 120 45 bank 10',
      'straight 60 up 26',
      'glide 90 down 26',
      'straight 60 boost items',
      'right 90 40',
      'left 45 60 dirt',
      'right 135 50 bank 10 cut coins',
      'straight 80 up 8',
      'right 60 60',
      'left 30 80',
      'right 60 60 boost',
      'straight 40 down 8',
    ],
  },
  {
    id: 'hotel', name: 'MONSTER HOTEL', cup: 1, theme: 'hotel', laps: 3, width: 22,
    course: [
      'straight 90 items',
      'left 90 35 bank 8',
      'straight 60 tunnel hazard:ghost 3',
      'right 90 35',
      'straight 60 up 10 coins',
      'jump 26',
      'straight 40 boost',
      'left 135 40 bank 14',
      'straight 70 hazard:ghost 2 items',
      'right 90 60',
      'left 135 40 bank 10 cut',
      'straight 60 down 10 boost',
      'left 90 45',
      'straight 50 coins',
      'left 90 50',
    ],
  },
  {
    id: 'volcano', name: 'LAVA RUSH', cup: 1, theme: 'volcano', laps: 3, width: 24,
    course: [
      'straight 100 items',
      'right 90 50 bank 8',
      'straight 70 fall hazard:geyser 2 coins',
      'left 60 60 fall',
      'straight 40',
      'jump 36',
      'straight 60 boost',
      'right 135 40 bank 12',
      'straight 80 up 16 hazard:roller 2',
      'right 45 60',
      'straight 40 down 16 items',
      'left 90 50 fall',
      'right 120 45 bank 10 cut',
      'straight 80 boost2 coins',
      'right 120 55',
      'straight 40',
    ],
  },
  // ===================== 3. GALAXY CUP =====================
  {
    id: 'coral', name: 'CORAL DOME', cup: 2, theme: 'underwater', laps: 3, width: 24,
    course: [
      'straight 100 items anti',
      'left 90 50 bank 10',
      'straight 50 coins',
      'loop 24',
      'straight 60 boost hazard:sweeper 2',
      'right 120 45 bank 14 anti',
      'straight 80 down 10 items',
      'left 45 60',
      'right 90 40',
      'straight 60 up 10 coins',
      'jump 30',
      'straight 50 boost',
      'right 135 50 bank 12',
      'straight 80 hazard:sweeper 2',
      'right 150 50',
      'straight 40',
    ],
  },
  {
    id: 'lab', name: 'LAB 13', cup: 2, theme: 'lab', laps: 3, width: 20,
    course: [
      'straight 80 items',
      'right 90 30',
      'straight 60 tunnel hazard:crusher 2',
      'left 90 30',
      'straight 50 tunnel coins',
      'right 90 30',
      'straight 70 hazard:sweeper 2',
      'right 90 35 boost',
      'straight 50',
      'jump 24',
      'straight 60 items',
      'left 90 35',
      'straight 50 tunnel hazard:crusher 2',
      'right 135 40 bank 10',
      'straight 70 boost coins',
      'right 90 35',
      'straight 50',
      'right 45 50',
    ],
  },
  {
    id: 'space', name: 'STAR STATION', cup: 2, theme: 'space', laps: 3, width: 24,
    course: [
      'straight 100 items fall',
      'left 60 50 fall',
      'twist 150 boost',
      'straight 80 fall coins',
      'right 120 45 bank 20 anti fall',
      'loop 26 left',
      'straight 60 items fall',
      'left 90 60 fall',
      'straight 40 up 20 fall',
      'glide 110 down 20',
      'straight 60 boost fall',
      'right 135 45 bank 14 fall',
      'straight 80 up 20 fall coins',
      'right 90 50 fall',
      'straight 40 down 20 fall',
      'right 75 60 fall',
      'right 90 60 fall',
    ],
  },
  {
    id: 'sky', name: 'CLOUD CASTLE', cup: 2, theme: 'sky', laps: 3, width: 24,
    course: [
      'straight 100 items fall',
      'right 90 50 fall',
      'straight 60 up 24 coins',
      'glide 120 down 24',
      'straight 50 boost',
      'left 120 45 bank 10 fall',
      'straight 70 hazard:roller 2 items',
      'right 90 40 fall',
      'right 90 40 fall',
      'straight 60 up 12 boost',
      'jump 30',
      'left 60 60',
      'right 135 50 bank 10 fall coins',
      'straight 80 down 12 boost',
      'right 135 50',
    ],
  },
  // ===================== 4. SPECIAL CUP =====================
  {
    id: 'stadium', name: 'MEGA STADIUM', cup: 3, theme: 'stadium', laps: 3, width: 28, offroad: 6,
    course: [
      'straight 160 items2 coins',
      'right 90 45 up 7',
      'right 180 45 bank 10 up 7',
      'straight 60 boost',
      'jump 26',
      'straight 80 dirt',
      'left 180 45 bank 10 down 7',
      'left 90 45 down 7 items',
      'straight 40 ramp',
    ],
  },
  {
    id: 'factory', name: 'ROBOT FACTORY', cup: 3, theme: 'factory', laps: 3, width: 22,
    course: [
      'straight 90 items',
      'right 90 40',
      'straight 60 hazard:crusher 2 boost',
      'right 90 40',
      'loop 22 left',
      'straight 50 coins',
      'left 120 40 bank 12',
      'straight 70 tunnel hazard:crusher 2',
      'right 90 35',
      'straight 50 up 10 boost2',
      'jump 28',
      'straight 50 items down 10',
      'right 135 40 bank 10',
      'straight 70 hazard:sweeper 2 coins',
      'right 90 45',
      'left 45 60',
      'right 30 60',
    ],
  },
  {
    id: 'moon', name: 'MOON BASE', cup: 3, theme: 'moon', laps: 3, width: 28, offroad: 6,
    course: [
      'straight 120 items',
      'left 90 60',
      'straight 50',
      'jump 50',
      'straight 70 boost coins',
      'left 135 50 bank 8 cut',
      'straight 80 up 10',
      'jump 40',
      'straight 60 items',
      'right 90 50',
      'left 120 50 bank 10',
      'straight 100 down 10 boost hazard:roller 2',
      'left 105 60',
      'straight 60 coins',
    ],
  },
  {
    id: 'rainbow', name: 'RAINBOW SIGMA ROAD', cup: 3, theme: 'rainbow', laps: 2, width: 22,
    course: [
      'straight 120 items fall',
      'right 90 45 fall',
      'straight 60 boost fall',
      'loop 26 left',
      'straight 50 fall coins',
      'left 120 45 bank 15 fall',
      'twist 140 boost',
      'straight 50 fall',
      'right 135 40 bank 18 fall',
      'straight 60 up 30 fall items',
      'glide 130 down 30',
      'straight 60 boost2 fall',
      'left 60 60 fall',
      'right 180 50 bank 20 fall',
      'straight 90 fall coins',
      'jump 32',
      'straight 50 fall items',
      'right 90 50 fall',
      'right 45 70 fall',
    ],
  },
];

HG.CUPS = [
  { name: 'SIGMA CUP', icon: 'Σ', color: '#ffcc1a' },
  { name: 'TURBO CUP', icon: '🔥', color: '#ff6a2a' },
  { name: 'GALAXY CUP', icon: '🌌', color: '#8a5aff' },
  { name: 'SPECIAL CUP', icon: '🌈', color: '#ff4ad8' },
];

// ===================== BATTLE ARENAS =====================
//  size = how big, round = circle or square, pillars = [x, z, radius]
HG.ARENAS = [
  { id: 'square', name: 'SIGMA SQUARE', theme: 'city', arena: true, size: 70, round: false,
    pillars: [[0, 0, 7], [-35, -35, 4], [35, -35, 4], [-35, 35, 4], [35, 35, 4]], ramps: [[0, 40, 0], [0, -40, Math.PI], [40, 0, -Math.PI / 2], [-40, 0, Math.PI / 2]] },
  { id: 'bowl', name: 'BEACH BOWL', theme: 'beach', arena: true, size: 65, round: true,
    pillars: [[0, 0, 9], [30, 20, 3], [-30, 20, 3], [0, -35, 3]], ramps: [[25, -20, 2.4], [-25, -20, -2.4]] },
  { id: 'lavapit', name: 'LAVA PIT', theme: 'volcano', arena: true, size: 60, round: true,
    pillars: [[20, 0, 5], [-20, 0, 5], [0, 20, 5], [0, -20, 5]], ramps: [[38, 0, -Math.PI / 2], [-38, 0, Math.PI / 2]] },
  { id: 'crater', name: 'MOON CRATER', theme: 'moon', arena: true, size: 75, round: true,
    pillars: [[0, 0, 6], [40, 30, 5], [-40, -30, 5], [30, -40, 4], [-30, 40, 4]], ramps: [[0, 30, 0], [0, -30, Math.PI], [30, 0, -Math.PI / 2]] },
];
